resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.


   hostname: ${module.dev-instances.instancehostname}
    DOC
  filename = "../playbooks/ascs-infra-setup/group_vars/var2"
}
