---
- name: Infrastructure Deployment
  hosts: localhost
  collections:
   - cloud.terraform

  vars_prompt:

    - name: env
      prompt: Please confirm the Environmenr Development or Test to deploy?
      private: false



  vars:
    project_dir: "{{env}}/"

  tasks:

   - name: Basic deploy of an instance
     cloud.terraform.terraform:
      project_path: '{{ project_dir }}'
      state: present
      force_init: true

   - name: Remove Instance
     cloud.terraform.terraform:
      project_path: '{{ project_dir }}'
      state: absent
      force_init: true
     tags:
       - never
       - remove

   - name: Wait to Completely Provision Instances
     pause:
       minutes: 2

   - name: Refresh Inventory
     meta: refresh_inventory

